### ISSUE TITLE
Can't connect without permission to list databases

### ISSUE THREAD

**Issue by pnsantos** [le-yams/nbmongo#35]
Hi,

It seems that in order to establish a connection the plugin automatically tries to execute the command `listDatabases: 1` however the user I'm connecting with doesn't have permission to do that so I can't connect.

Is it possible to instead of doing `listDatabase: 1` do `getCollectionNames` for example? (or if `listDatabase` fails do `getCollectionNames`? (like in MongoHub where even though you can't see DB details, you can still list/view/edit collections ).

Using NB 8.0.2 with 8.1.0 NBMongo plugin.

**Comment by le-yams** [comment]
Hi Pedro,

Sorry for the late reply I was on vacation. 
Indeed, this call to the listDatabase command need to be removed. It comes from some legacy code to ensure the connection is working.
I'll try to patch the current version quickly, hopefullly the update might be available next week.
After that, if you specify a database on the connection uri it won't try to list the others databases. However if you don't specify a database it will assume you have the right to list the databases.

Regards,
Yann

**Comment by pnsantos** [comment]
Thx Yann!

**Comment by le-yams** [comment]
You're welcome ;-).
Actually, I have problems testing the fix. I'm no mongo admin and I don't know how to forbid the listDatabases command usage. I tried to create a simple user with a single "read" role on a single database but it still can use the command.
So I'm not able to recreate the issue conditions in order to formally validate the fix. Could you manually install the fixed version nbm ([see here](https://github.com/le-yams/nbmongo/releases/tag/nbmongo-8.1.2-rc1)) and tell me if the correction actually works ?

Regards,
Yann

**Comment by pnsantos** [comment]
Worked perfectly! 

Thanks a lot! NetBeans just got a little better :-)

**Comment by le-yams** [comment]
Cool, I just made the release and published it on the plugin center. It will be available for update as soon as the verification is done by the NetBeans guys ;-).

Regards,
Yann
